[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "EriAkane"
authors = [{name = "iShiKKi", email = "ishikkiakabane@gmail.com"}]
dynamic = ["version", "description"]
